server:
  port: 8081
spring:
  mvc:
    static-path-pattern: /**
  application:
    name: java-interview
  thymeleaf:
    prefix: classpath:/templates/
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://106.52.95.63:9001/eureka
